server:
  port: 8080
spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 100
    min-evictable-idle-time-millis: 1800000
    min-idle: 10
    password: imooc
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    url: jdbc:mysql://127.0.0.1:3306/imooc?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: imooc
    validation-query: select 1
mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*.xml

jwt:
  expiration: 10
  header: Authorization
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: '"auth/register"'
  secret: mySecret
  tokenHead: Bearer

logging:
  file: ${LOG_TEMP:./logs}/${spring.application.name}.log
  level:
    com.xiaojun: debug

zuul:
  routes:
    main-data:
      path: /api/main-data/**
      serviceId: demo1
    api-a:
      path: /cop/**
      serviceid: copper-purchase
    api-b:
      path: /cos/**
      serviceid: copper-server
    api-c:
      path: /web/**
      serviceid: copper-surface
    api-d:
      path: /ius-d/**
      serviceId: fast-auth-server
    api-e:
      path: /ss/**
      serviceId: storage-server
    api-f:
      path: /ss-cdw/**
      serviceId: storage-server-cdw
    api-g:
      path: /ius-s/**
      serviceId: storage-server-v
  max:
    host:
      connections: 500
  host:
      socket-timeout-millis: 600000
      connect-timeout-millis: 600000

security:
  basic:
   enabled: false

fast:
  auth:
    login:
      url: /ius/auth/login,/ius/auth/sigin
    logout:
      url: /ius/auth/logout,/ius/auth/signout
    thirdAuth:
      url: /ius/thirdAuth/webAuth,/ius/thirdAuth/registerAccount
    thirdUser:
      url: /ius/thirdAuth/getUserInfo